services:
  db:
    image: postgres
    shm_size: 256mb
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '1.0'
